# Generated by Django 5.2.7 on 2025-10-18 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('address', models.TextField(verbose_name='Adresse')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('whatsapp_number', models.CharField(max_length=20, verbose_name='Numéro WhatsApp')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('logo', models.ImageField(blank=True, upload_to='logos/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': "Information de l'entreprise",
                'verbose_name_plural': "Informations de l'entreprise",
            },
        ),
        migrations.CreateModel(
            name='ImmigrationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('birth_date', models.DateField(verbose_name='Date de naissance')),
                ('birth_place', models.CharField(max_length=200, verbose_name='Lieu de naissance')),
                ('height', models.PositiveIntegerField(verbose_name='Taille (cm)')),
                ('weight', models.PositiveIntegerField(verbose_name='Poids (kg)')),
                ('marital_status', models.CharField(choices=[('single', 'Célibataire'), ('married', 'Marié(e)'), ('divorced', 'Divorcé(e)'), ('widowed', 'Veuf/Veuve'), ('separated', 'Séparé(e)')], max_length=20, verbose_name='Situation matrimoniale')),
                ('address', models.TextField(verbose_name='Adresse complète')),
                ('country_of_residence', models.CharField(max_length=100, verbose_name='Pays de résidence')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Format de téléphone invalide', regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone')),
                ('father_name', models.CharField(max_length=200, verbose_name='Nom du père')),
                ('mother_name', models.CharField(max_length=200, verbose_name='Nom de la mère')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_generated', models.BooleanField(default=False, verbose_name='PDF généré')),
            ],
            options={
                'verbose_name': "Candidature d'immigration",
                'verbose_name_plural': "Candidatures d'immigration",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PassportInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro de passeport ne peut contenir que des lettres majuscules et des chiffres', regex='^[A-Z0-9]+$')], verbose_name='Numéro de passeport')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('birth_place', models.CharField(max_length=200, verbose_name='Lieu de naissance')),
                ('birth_date', models.DateField(verbose_name='Date de naissance')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('nationality', models.CharField(max_length=100, verbose_name='Nationalité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Information de passeport',
                'verbose_name_plural': 'Informations de passeports',
                'ordering': ['-created_at'],
            },
        ),
    ]
