# Generated by Django 5.2.7 on 2026-02-15 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_number', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro de visa ne peut contenir que des lettres majuscules, chiffres et tirets', regex='^[A-Z0-9\\-]+$')], verbose_name='Numéro de visa')),
                ('visa_type', models.CharField(choices=[('tourist', 'Touristique'), ('work', 'Travail'), ('student', 'Étudiant'), ('business', 'Affaires'), ('transit', 'Transit'), ('permanent', 'Résidence permanente'), ('other', 'Autre')], max_length=20, verbose_name='Type de visa')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('expired', 'Expiré'), ('pending', 'En attente'), ('approved', 'Approuvé')], default='active', max_length=20, verbose_name='Statut')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('nationality', models.CharField(max_length=100, verbose_name='Nationalité')),
                ('passport_number', models.CharField(max_length=20, verbose_name='Numéro de passeport')),
                ('issue_date', models.DateField(verbose_name='Date de délivrance')),
                ('expiry_date', models.DateField(verbose_name="Date d'expiration")),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('birth_place', models.CharField(blank=True, max_length=200, verbose_name='Lieu de naissance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Information de visa',
                'verbose_name_plural': 'Informations de visas',
                'ordering': ['-created_at'],
            },
        ),
    ]
