# Generated by Django 5.2.7 on 2026-02-15 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_add_visa_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='immigrationapplication',
            name='id_document_recto',
            field=models.ImageField(blank=True, null=True, upload_to='applications/id_recto/', verbose_name="Pièce d'identité (recto)"),
        ),
        migrations.AddField(
            model_name='immigrationapplication',
            name='id_document_verso',
            field=models.ImageField(blank=True, null=True, upload_to='applications/id_verso/', verbose_name="Pièce d'identité (verso)"),
        ),
        migrations.AddField(
            model_name='immigrationapplication',
            name='profession',
            field=models.CharField(blank=True, max_length=200, verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='passport_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Format du numéro de passeport : 2 lettres suivies de 6 chiffres (ex: NB442748)', regex='^[A-Z]{2}[0-9]{6}$')], verbose_name='Numéro de passeport'),
        ),
        migrations.AlterField(
            model_name='visainfo',
            name='visa_number',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Format du numéro de visa : une lettre suivie de 9 chiffres (ex: E981296032)', regex='^[A-Z][0-9]{9}$')], verbose_name='Numéro de visa'),
        ),
    ]
